/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package telas;

import database.DBEndereco;
import database.DBMException;
import database.DBMLocalizador;
import database.DBMPersistor;
import database.DBPessoa;
import dizimo.Funcao;
import java.awt.Component;
import java.awt.Container;
import java.text.NumberFormat;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFormattedTextField;
import javax.swing.JOptionPane;
import javax.swing.text.NumberFormatter;

/**
 *
 * @author 0132944
 */
public class TelaPessoa extends javax.swing.JDialog {
    private Funcao fun;
    private DBPessoa pessoa;
    private DBEndereco endereco;
    private boolean OK;
    private DBMLocalizador<DBPessoa> lPessoa;
    private DBMLocalizador<DBEndereco> lEndereco;
    private DBMPersistor pPessoa;
    private int codigo;
    private List<DBEndereco> enderecos;

    /**
     * Creates new form TelaPessoa
     */
    public TelaPessoa(java.awt.Dialog parent, boolean modal, Funcao fun, int codigo) {
        super(parent, modal);
        this.fun = fun;
        this.codigo = codigo;
        OK = false;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tfNatural = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        tfInstrução = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        tfProfissao = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        cbPrimeiraComunhao = new javax.swing.JCheckBox();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cbCrisma = new javax.swing.JCheckBox();
        cbPraticante = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        btOK = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        ftTelefone = new javax.swing.JFormattedTextField();
        jLabel9 = new javax.swing.JLabel();
        ftNascimento = new javax.swing.JFormattedTextField();
        jLabel10 = new javax.swing.JLabel();
        coEndereco = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        coEstadoCivil = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        cbCasamentoCivil = new javax.swing.JCheckBox();
        cbCasamentoReligioso = new javax.swing.JCheckBox();
        coCasa = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        tfNome = new javax.swing.JTextField();
        coSalario = new javax.swing.JComboBox<>();
        tfReligiao = new javax.swing.JTextField();
        ftNumCasa = new javax.swing.JFormattedTextField(new NumberFormatter(NumberFormat.getInstance()));
        ftDataSocio = new javax.swing.JFormattedTextField();
        jLabel15 = new javax.swing.JLabel();
        ftNumFichaAtual = new javax.swing.JFormattedTextField(new NumberFormatter(NumberFormat.getInstance()));
        ftCodigo = new javax.swing.JFormattedTextField(new NumberFormatter(NumberFormat.getInstance()));

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Pessoas");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel6.setText("Nascimento");

        jLabel5.setText("Telefone");

        jLabel4.setText("Núm.ficha atual");

        cbPrimeiraComunhao.setText("Primeira Comunhão");

        jLabel3.setText("Número casa");

        jLabel2.setText(" Nome");

        cbCrisma.setText("Crisma");

        cbPraticante.setText("Praticante");

        jLabel1.setText("Código");

        jLabel7.setText("Natural");

        btOK.setText("OK");
        btOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btOKActionPerformed(evt);
            }
        });

        jLabel8.setText("Religião");

        ftTelefone.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getIntegerInstance())));

        jLabel9.setText("Instrução");

        ftNascimento.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("dd/MM/yyyy"))));

        jLabel10.setText("Profissão");

        jLabel11.setText("Endereço");

        coEstadoCivil.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Solteiro", "Casado", "Viúvo", "Separado" }));

        jLabel12.setText("Estado Civil");

        cbCasamentoCivil.setText("Casamento Civil");

        cbCasamentoReligioso.setText("Casamento Religioso");

        coCasa.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Própria", "Alugada", "Financiada" }));

        jLabel13.setText("Casa");

        jLabel14.setText("Salário");

        coSalario.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mínimo", "Mais", "Menos" }));

        ftNumCasa.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getIntegerInstance())));

        ftDataSocio.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter()));

        jLabel15.setText("Socio desde");

        ftNumFichaAtual.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getIntegerInstance())));

        ftCodigo.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getIntegerInstance())));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1)
                    .addComponent(jLabel11)
                    .addComponent(jLabel3)
                    .addComponent(jLabel12)
                    .addComponent(jLabel13)
                    .addComponent(jLabel14)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btOK))
                    .addComponent(tfProfissao)
                    .addComponent(tfNatural, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(coSalario, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(coEndereco, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cbCasamentoCivil)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cbCasamentoReligioso))
                    .addComponent(coCasa, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(coEstadoCivil, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tfNome)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(ftNumCasa, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ftTelefone))
                    .addComponent(tfReligiao)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cbPrimeiraComunhao)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cbCrisma))
                    .addComponent(tfInstrução)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(ftCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel4))
                            .addComponent(cbPraticante))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ftNumFichaAtual, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(ftNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 74, Short.MAX_VALUE)
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ftDataSocio, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel4)
                    .addComponent(ftNumFichaAtual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ftCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(coEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(ftTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ftNumCasa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(coEstadoCivil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbCasamentoCivil)
                    .addComponent(cbCasamentoReligioso))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(coCasa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(coSalario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel15)
                        .addComponent(ftDataSocio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel6)
                        .addComponent(ftNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfNatural, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfReligiao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbPrimeiraComunhao)
                    .addComponent(cbCrisma))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbPraticante)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfInstrução, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfProfissao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btOK)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public boolean isOK() {
        return OK;
    }

    public DBPessoa getPes() {
        return pessoa;
    }

    private void btOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btOKActionPerformed
        dispose();
        OK = true;
        //Carrega os campos do objeto com o conteúdo da tela
        pessoa.setCodigo(toInteger(ftCodigo));
        pessoa.setNumFichaAtual(toInteger(ftNumFichaAtual));
        pessoa.setNome(tfNome.getText());
        try {
            enderecos = lEndereco.procuraRegistros("logradouro LIKE ?", coEndereco.getSelectedItem());
            endereco = enderecos.get(0);
        } catch (DBMException ex) {
        }
        pessoa.setEndereco(endereco);
        pessoa.setNumCasa(toInteger(ftNumCasa));
        pessoa.setTelefone(toInteger(ftTelefone));
        pessoa.setEstadoCivil((String) coEstadoCivil.getSelectedItem());
        pessoa.setCasamentoReligioso(cbCasamentoReligioso.isSelected());
        pessoa.setCasamentoCivil(cbCasamentoCivil.isSelected());
        pessoa.setCasa((String) coCasa.getSelectedItem());
        pessoa.setSalario((String) coSalario.getSelectedItem());
        pessoa.setNascimento((Date) ftNascimento.getValue());
        pessoa.setDataSocio((Date) ftDataSocio.getValue());
        pessoa.setNatural(tfNatural.getText());
        pessoa.setReligiao(tfReligiao.getText());
        pessoa.setPrimeiraComunhao(cbPrimeiraComunhao.isSelected());
        pessoa.setCrisma(cbCrisma.isSelected());
        pessoa.setPraticante(cbPraticante.isSelected());
        pessoa.setInstrucao(tfInstrução.getText());
        pessoa.setProfissao(tfProfissao.getText());
        try {

            switch(fun){
                case INCLUSAO:
                    pPessoa.insere();
                    break;
                case ALTERACAO:
                    pPessoa.altera();
                    break;
                case EXCLUSAO:
                    pPessoa.exclui();
                    break;
            }
        } catch (DBMException e) {
        }
    }//GEN-LAST:event_btOKActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        try {
            //Se é inclusão apenas cria um novo objeto
            if(fun == Funcao.INCLUSAO){
                pessoa = new DBPessoa();
            }else{
                //para demais funções busca o registro no banco
                lPessoa = new DBMLocalizador<>(DBPessoa.class);
                pessoa = lPessoa.procuraRegistro(codigo);
                if(pessoa == null){
                    JOptionPane.showMessageDialog(this, "Pessoa de código " + codigo + " não foi lida corretamente do banco!");
                    dispose();
                }
            }
            pPessoa = new DBMPersistor(pessoa);
            //Prepara montagem das opções de endereços
            lEndereco = new DBMLocalizador<>(DBEndereco.class);
            enderecos = lEndereco.procuraRegistros("");
            endereco = lEndereco.procuraRegistro(pessoa.getIntEndereco());

        } catch (DBMException e) {
        }
        //se é função que não aceita os dados
        if(fun == Funcao.CONSULTA || fun == Funcao.EXCLUSAO){
            //desabilita todos os campos da tela
            habilitaComponentes(this, false);
        }
        //carrega os campos da tela com o conteúdo do objeto
        ftCodigo.setValue(pessoa.getCodigo().longValue());
        ftNumFichaAtual.setValue(pessoa.getNumFichaAtual().longValue());
        tfNome.setText(pessoa.getNome());
        for (DBEndereco end : enderecos) {
            coEndereco.addItem(end.getLogradouro());
        }
        if(endereco != null){
            coEndereco.setSelectedItem(endereco.getLogradouro());
        }else{
            coEndereco.setSelectedItem(0);
        }
        ftNumCasa.setValue(pessoa.getNumCasa().longValue());
        ftTelefone.setValue(pessoa.getTelefone().longValue());
        coEstadoCivil.setSelectedItem(pessoa.getEstadoCivil());
        cbCasamentoCivil.setSelected(pessoa.isCasamentoCivil());
        cbCasamentoReligioso.setSelected(pessoa.isCasamentoReligioso());
        coCasa.setSelectedItem(pessoa.getCasa());
        coSalario.setSelectedItem(pessoa.getSalario());
        ftNascimento.setValue(pessoa.getNascimento());
        ftDataSocio.setValue(pessoa.getDataSocio());
        tfNatural.setText(pessoa.getNatural());
        tfReligiao.setText(pessoa.getReligiao());
        cbPrimeiraComunhao.setSelected(pessoa.isPrimeiraComunhao());
        cbCrisma.setSelected(pessoa.isCrisma());
        cbPraticante.setSelected(pessoa.isPraticante());
        tfInstrução.setText(pessoa.getInstrucao());
        tfProfissao.setText(pessoa.getProfissao());
    }//GEN-LAST:event_formWindowOpened

    private void habilitaComponentes(Container container, boolean enable) {
        Component[] components = container.getComponents();
        for (Component component : components) {
            component.setEnabled(enable);
            if (component instanceof Container) {
                habilitaComponentes((Container)component, enable);
            }
        }
    }
    
    private Integer toInteger(JFormattedTextField field){
        return ((Long) field.getValue()).intValue();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btOK;
    private javax.swing.JCheckBox cbCasamentoCivil;
    private javax.swing.JCheckBox cbCasamentoReligioso;
    private javax.swing.JCheckBox cbCrisma;
    private javax.swing.JCheckBox cbPraticante;
    private javax.swing.JCheckBox cbPrimeiraComunhao;
    private javax.swing.JComboBox<String> coCasa;
    private javax.swing.JComboBox<String> coEndereco;
    private javax.swing.JComboBox<String> coEstadoCivil;
    private javax.swing.JComboBox<String> coSalario;
    private javax.swing.JFormattedTextField ftCodigo;
    private javax.swing.JFormattedTextField ftDataSocio;
    private javax.swing.JFormattedTextField ftNascimento;
    private javax.swing.JFormattedTextField ftNumCasa;
    private javax.swing.JFormattedTextField ftNumFichaAtual;
    private javax.swing.JFormattedTextField ftTelefone;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField tfInstrução;
    private javax.swing.JTextField tfNatural;
    private javax.swing.JTextField tfNome;
    private javax.swing.JTextField tfProfissao;
    private javax.swing.JTextField tfReligiao;
    // End of variables declaration//GEN-END:variables
}
