/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package telas;

import database.DBEndereco;
import database.DBMException;
import database.DBMLocalizador;
import database.DBMPersistor;
import database.DBPessoa;
import dizimo.Funcao;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFormattedTextField;
import javax.swing.JOptionPane;
import sun.awt.CausedFocusEvent;

/**
 *
 * @author Usuario
 */
public class TelaEndereco extends javax.swing.JDialog {
    private Funcao fun;
    private boolean OK;
    private boolean validado;
    private DBEndereco endereco;
    private DBMLocalizador<DBEndereco> lEndereco;
    private DBMLocalizador<DBPessoa> lPessoa;
    private ArrayList<DBPessoa> listPes;
    private DBMPersistor pEndereco;
    private int codigo;


    /**
     * Creates new form TelaEndereco
     */
    public TelaEndereco(java.awt.Dialog parent, boolean modal, Funcao fun, int codigo) {
        super(parent, modal);
        this.fun = fun;
        this.codigo = codigo;
        OK = false;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        tfBairro = new javax.swing.JTextField();
        btOK = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        tfLogradouro = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        tfDescComplem = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        tfVila = new javax.swing.JTextField();
        ftCodigo = new javax.swing.JFormattedTextField();
        ftCep = new javax.swing.JFormattedTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Endereço");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel6.setText("Bairro");

        btOK.setText("OK");
        btOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btOKActionPerformed(evt);
            }
        });

        jLabel1.setText("Código");

        jLabel2.setText("Logradouro");

        jLabel3.setText("CEP");

        tfLogradouro.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                tfLogradouroFocusLost(evt);
            }
        });

        jLabel4.setText("Desc.Complementar");

        jLabel5.setText("Vila");

        ftCodigo.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getIntegerInstance())));
        ftCodigo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                ftCodigoFocusLost(evt);
            }
        });

        ftCep.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getIntegerInstance())));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btOK))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(78, 78, 78)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(51, 51, 51)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel4)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfBairro)
                            .addComponent(tfVila)
                            .addComponent(tfDescComplem)
                            .addComponent(tfLogradouro)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ftCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ftCep, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 168, Short.MAX_VALUE)))))
                .addGap(24, 24, 24))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(ftCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfLogradouro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(ftCep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(tfDescComplem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(tfVila, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(tfBairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btOK)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btOKActionPerformed
        if(!validaFtCodigo()){
            ftCodigo.requestFocus();
            return;
        }
        if(!validaTfLogradouro()){
            tfLogradouro.requestFocus();
            return;
        }
        dispose();
        OK = true;
        //Carrega os campos do objeto com o conteúdo da tela
        endereco.setBairro(tfBairro.getText());
        endereco.setCep(toInteger(ftCep));
        endereco.setCodigo(toInteger(ftCodigo));
        endereco.setLogradouro(tfLogradouro.getText());
        endereco.setDescricaoComplementar(tfDescComplem.getText());
        endereco.setVila(tfVila.getText());
        try {

            switch(fun){
                case INCLUSAO:
                    pEndereco.insere();
                    break;
                case ALTERACAO:
                    pEndereco.altera();
                    break;
                case EXCLUSAO:
                    pEndereco.exclui();
                    break;
            }
        } catch (DBMException e) {
        }
    }//GEN-LAST:event_btOKActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        try {
            //Prepara a classe que localiza registros no banco
            lEndereco = new DBMLocalizador<>(DBEndereco.class);
            //Se é inclusão apenas cria um novo objeto
            if(fun == Funcao.INCLUSAO){
                endereco = new DBEndereco();
            }else{
            //Se é inclusão apenas cria um novo objeto
                //para demais funções busca o registro no banco
                endereco = lEndereco.procuraRegistro(codigo);
                if(endereco == null){
                    JOptionPane.showMessageDialog(this, "Endereço de código " + codigo + " não foi lido corretamente do banco!");
                    dispose();
                    return;
                }
                //Se estiver na exclusão
                if(fun == Funcao.EXCLUSAO){
                    lPessoa = new DBMLocalizador<>(DBPessoa.class);
                    listPes = lPessoa.procuraRegistros("intEndereco = ?", codigo);
                    if(listPes != null){
                        JOptionPane.showMessageDialog(this, "Endereço de código " + codigo + " ainda é utilizado na pessoa " + listPes.get(0).getCodigo() + "-"+ listPes.get(0).getNome() + "!\nPor este motivo não pode ser excluído!");
                        dispose();
                        return;
                    }
                }
            }
            pEndereco = new DBMPersistor(endereco);
        } catch (DBMException e) {
        }
        //se é função que não aceita os dados
        if(fun == Funcao.CONSULTA || fun == Funcao.EXCLUSAO){
            //desabilita todos os campos da tela
            tfBairro.setEnabled(false);
            ftCep.setEnabled(false);
            ftCodigo.setEnabled(false);
            tfLogradouro.setEnabled(false);
            tfDescComplem.setEnabled(false);
            tfVila.setEnabled(false);
        }
        //se é função que não aceita chave
        if(fun == Funcao.ALTERACAO){
            ftCodigo.setEnabled(false);
        }
        //carrega os campos da tela com o conteúdo do objeto
        tfBairro.setText(endereco.getBairro());
        ftCep.setValue(endereco.getCep().longValue());
        ftCodigo.setValue(endereco.getCodigo().longValue());
        tfLogradouro.setText(endereco.getLogradouro());
        tfDescComplem.setText(endereco.getDescricaoComplementar());
        tfVila.setText(endereco.getVila());
    }//GEN-LAST:event_formWindowOpened

    private void ftCodigoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ftCodigoFocusLost
        if(evt.isTemporary())return;
        if(((CausedFocusEvent) evt).getCause() == CausedFocusEvent.Cause.CLEAR_GLOBAL_FOCUS_OWNER)return;
        validaFtCodigo();
    }//GEN-LAST:event_ftCodigoFocusLost

    private void tfLogradouroFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfLogradouroFocusLost
        if(evt.isTemporary())return;
        if(((CausedFocusEvent) evt).getCause() == CausedFocusEvent.Cause.CLEAR_GLOBAL_FOCUS_OWNER)return;
        validaTfLogradouro();
    }//GEN-LAST:event_tfLogradouroFocusLost

    private boolean validaFtCodigo(){
        //Se não estiver na inclusão
        if(fun != Funcao.INCLUSAO){
            return true;
        }
        int cod;
        //Se código em branco ou zerado
        if(ftCodigo.getText().isEmpty() || (cod = Integer.parseInt(ftCodigo.getText())) == 0){
            JOptionPane.showMessageDialog(this, "Código deve ser informado!");
            return false;
        }
        try {
            if(lEndereco.procuraRegistro(cod) != null){
                JOptionPane.showMessageDialog(this, "Endereço de código " + cod + " já foi cadastrado!\nUtilize outro código!");
                return false;
            }
        } catch (DBMException ex) {
            Logger.getLogger(TelaEndereco.class.getName()).log(Level.SEVERE, null, ex);
        }
        return true;
    }

    private boolean validaTfLogradouro(){
        //Se não estiver na inclusão ou na alteração
        if(fun == Funcao.INCLUSAO || fun == Funcao.ALTERACAO){
            //Se código em branco ou zerado
            if(tfLogradouro.getText().isEmpty()){
                JOptionPane.showMessageDialog(this, "Logradouro deve ser informado!");
                return false;
            }
        }
        return true;
    }

    private Integer toInteger(JFormattedTextField field){
        return ((Long) field.getValue()).intValue();
    }

    public boolean isOK() {
        return OK;
    }

    public DBEndereco getEnd() {
        return endereco;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btOK;
    private javax.swing.JFormattedTextField ftCep;
    private javax.swing.JFormattedTextField ftCodigo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField tfBairro;
    private javax.swing.JTextField tfDescComplem;
    private javax.swing.JTextField tfLogradouro;
    private javax.swing.JTextField tfVila;
    // End of variables declaration//GEN-END:variables
}
