/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package telas;

import database.DBEndereco;
import database.DBFicha;
import database.DBMException;
import database.DBMLocalizador;
import database.DBMPersistor;
import database.DBPessoa;
import dizimo.Funcao;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Lucas
 */
public class TelaFicha extends javax.swing.JDialog {
    private Funcao fun;
    private int codigo;
    
    private DBFicha ficha;
    private DBMLocalizador<DBFicha> lFicha;
    private DBMPersistor pFicha;
    
    private DBPessoa responsavel;
    private DBMLocalizador<DBPessoa> lPessoa;
    
    private DBEndereco endereco;
    private DBMLocalizador<DBEndereco> lEdereco;

    /**
     * Creates new form TelaFichaNova
     */
    public TelaFicha(java.awt.Dialog parent, boolean modal, Funcao fun, int codigo) {
        super(parent, modal);
        this.fun = fun;
        //Se não for função de consulta
        if(fun!=Funcao.CONSULTA){
            try {
                pFicha = new DBMPersistor(ficha);
            } catch (DBMException ex) {
                Logger.getLogger(TelaFicha.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        initComponents();     
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbHistorico = new javax.swing.JLabel();
        pbPessoas = new javax.swing.JButton();
        pbOk = new javax.swing.JButton();
        lbNumero = new javax.swing.JLabel();
        tfNumero = new javax.swing.JTextField();
        tfResponsavel = new javax.swing.JTextField();
        lbResponsavel = new javax.swing.JLabel();
        lbEndereco = new javax.swing.JLabel();
        tfEndereco = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbPagamentos = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tfObservacoes = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Manutenção da ficha");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        lbHistorico.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbHistorico.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbHistorico.setText("Histórico das contribuições");

        pbPessoas.setText("Pessoas");
        pbPessoas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pbPessoasActionPerformed(evt);
            }
        });

        pbOk.setText("OK");
        pbOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pbOkActionPerformed(evt);
            }
        });

        lbNumero.setText("Número");

        tfNumero.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                tfNumeroFocusLost(evt);
            }
        });

        tfResponsavel.setEditable(false);

        lbResponsavel.setText("Responsável");

        lbEndereco.setText("Endereço");

        tfEndereco.setEditable(false);

        tbPagamentos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Ano", "Jan.", "Fev.", "Mar.", "Abr.", "Mai.", "Jun.", "Jul.", "Ago.", "Set.", "Out", "Nov.", "Dez.", "Total R$"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Float.class
            };
            boolean[] canEdit = new boolean [] {
                false, true, true, true, true, true, true, true, true, true, true, true, true, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tbPagamentos);

        tfObservacoes.setColumns(20);
        tfObservacoes.setRows(5);
        jScrollPane2.setViewportView(tfObservacoes);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbEndereco)
                    .addComponent(lbNumero)
                    .addComponent(lbResponsavel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tfEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfResponsavel)
                            .addComponent(tfNumero))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pbPessoas)))
                .addContainerGap(293, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addComponent(lbHistorico, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(pbOk)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbNumero)
                    .addComponent(tfNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfResponsavel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbResponsavel)
                    .addComponent(pbPessoas))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbEndereco)
                    .addComponent(tfEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbHistorico)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(pbOk)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pbPessoasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pbPessoasActionPerformed
        TelaPessoasFicha tPessoas = new TelaPessoasFicha(this, true);
        tPessoas.setVisible(true);
    }//GEN-LAST:event_pbPessoasActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        if(fun == Funcao.INCLUSAO){
            ficha = new DBFicha();
            //Desabilita campos deixando apenas a chave informada
            tfResponsavel.setEnabled(false);
            tfEndereco.setEnabled(false);
            tbPagamentos.setEnabled(false);
            pbPessoas.setEnabled(false);
            tfObservacoes.setEnabled(false);
            //Habilita campos da chave do registro
            tfNumero.setEnabled(true);
        }else{
            try {
                //Busca a ficha recebida por parâmetro
                lFicha = new DBMLocalizador<>(DBFicha.class);
                ficha = lFicha.procuraRegistro(codigo);
                //Carrega dados da ficha lida para a manutenção
                tfNumero.setText(ficha.getCodigo().toString());
            } catch (DBMException ex) {
                Logger.getLogger(TelaFicha.class.getName()).log(Level.SEVERE, null, ex);
                JOptionPane.showMessageDialog(null, "Não foi localizada a ficha no banco!");
                dispose();
            }
        }
        //Carrega conteúdo padrão para a lista de pagamentos
        DefaultTableModel dtmPagamentos = (DefaultTableModel) tbPagamentos.getModel();
        Object[] rowDefault = {2017, "-", "-", "-", "-", "-", "-", "-", "-", "-", "-", "-", "-",0};
        for (int i = 0; i < 20; i++) {
            rowDefault[0] = 2017 - i;
            dtmPagamentos.addRow(rowDefault);
        }
    }//GEN-LAST:event_formWindowOpened

    private void tfNumeroFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfNumeroFocusLost
        //Habilita campos de dados
        tbPagamentos.setEnabled(true);
        pbPessoas.setEnabled(true);
        tfObservacoes.setEnabled(true);
        //Desabilita campos da chave do registro
        tfNumero.setEnabled(false);        
    }//GEN-LAST:event_tfNumeroFocusLost

    private void pbOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pbOkActionPerformed
        //Carrega dados da manuteção para a ficha
        ficha.setCodigo(Integer.parseInt(tfNumero.getText()));
        ficha.setObservacoes(tfObservacoes.getText());
        if(fun==Funcao.INCLUSAO){
            try {
                pFicha.insere();
                dispose();
            } catch (DBMException ex) {
                Logger.getLogger(TelaFicha.class.getName()).log(Level.SEVERE, null, ex);
            }            
        }
    }//GEN-LAST:event_pbOkActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaFicha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaFicha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaFicha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaFicha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                TelaFicha dialog = new TelaFicha(new javax.swing.JDialog(), true, Funcao.INCLUSAO, 0);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lbEndereco;
    private javax.swing.JLabel lbHistorico;
    private javax.swing.JLabel lbNumero;
    private javax.swing.JLabel lbResponsavel;
    private javax.swing.JButton pbOk;
    private javax.swing.JButton pbPessoas;
    private javax.swing.JTable tbPagamentos;
    private javax.swing.JTextField tfEndereco;
    private javax.swing.JTextField tfNumero;
    private javax.swing.JTextArea tfObservacoes;
    private javax.swing.JTextField tfResponsavel;
    // End of variables declaration//GEN-END:variables
}
